const DATA = [
  {
    "id": "AGS-2026-001",
    "fecha": "2026-03-01",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "\"Reforma al artículo 124 de la Ley de Movilidad y Seguridad Vial del Estado de Aguascalientes para incorporar a las mujeres embarazadas como beneficiarias de tarifas preferenciales: 50% de descuento en transporte colectivo y servicio gratuito en taxi para traslados a instituciones de salud\"",
    "resumen": "Iniciativa para beneficiar a mujeres embarazadas con tarifas reducidas en el transporte público. Establece 50% de descuento en transporte colectivo urbano y foráneo durante la gestación (acreditable con constancia médica) y viajes gratuitos en taxi hacia instituciones de salud para atención médica relacionada con el embarazo o urgencias obstétricas.",
    "link_documento": "",
    "link_portal": "https://congresoags.gob.mx/agenda_legislativa/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | Presentada por diputado Humberto Montero de Alba con apoyo de Jetsy Sánchez",
    "estado": "Aguascalientes"
  },
  {
    "id": "AGS-2025-006",
    "fecha": "2025-12-12",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_SEG",
    "extracto": "\"Nueva Ley de Movilidad y Seguridad Vial del Estado de Aguascalientes que contempla la transformación de la Coordinación Estatal de Movilidad (CMOV) en la Agencia Estatal de Movilidad, organismo técnico que centralizará funciones dispersas y dirigirá con visión especializada el sistema de movilidad estatal\"",
    "resumen": "Reforma estructural aprobada por unanimidad que sustituye la Ley de Movilidad anterior. Crea la Agencia Estatal de Movilidad como organismo técnico con atribuciones de regulación",
    "link_documento": " autorización y supervisión integral del sistema de movilidad. Actualiza terminología",
    "link_portal": " regula empresas de grúas",
    "fuente_verificada": " simplifica trámites para personas con movilidad limitada y organiza los servicios auxiliares de tránsito. Dictamen aprobado el 11/12/2025 y decreto publicado el 23/01/2026.",
    "notas": "https://tramites.aguascalientes.gob.mx/download/normateca/D20260123084749_LEY%20DE%20MOVILIDAD%20Y%20SEGURIDAD%20VIAL%20DEL%20ESTADO%20DE%20AGUASCALIENTES.pdf",
    "estado": "Aguascalientes"
  },
  {
    "id": "AGS-2025-005",
    "fecha": "2025-11-01",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_SEG",
    "extracto": "\"Establece la obligatoriedad del botón de alerta en unidades de transporte contratadas a través de plataformas digitales y homologa criterios con el transporte público convencional, además de exigir la instalación de GPS en los vehículos\"",
    "resumen": "La Comisión de Movilidad Sustentable y Transporte Público aprobó reforma a la Ley de Movilidad para hacer obligatorio el botón de alerta (físico o digital) y GPS en todos los vehículos de transporte de personas y plataformas como Uber y Didi. También exige que los vehículos exhiban número económico u holograma de identificación visible. Aprobada en la 8ª sesión ordinaria de la LXVI Legislatura.",
    "link_documento": "",
    "link_portal": "https://congresoags.gob.mx/boletines_de_prensa/boletin/6222",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte | 8ª sesión ordinaria de la LXVI Legislatura. Se asigna subtema secundario MOV_SEG por el componente de seguridad de usuarios.",
    "estado": "Aguascalientes"
  },
  {
    "id": "AGS-2025-004",
    "fecha": "2025-10-01",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "\"Modificación al artículo 11 de la Ley de Ingresos 2025 que permitirá a la Secretaría de Finanzas otorgar descuentos de hasta 30 por ciento en los pagos por transmisión de concesiones de transporte público en las modalidades de taxi y colectivo foráneo (combis)\"",
    "resumen": "Reforma a la Ley de Ingresos 2025 aprobada por unanimidad en pleno para incentivar la transmisión de concesiones de transporte público. Reduce en 30% los costos de traspaso de concesiones de taxi y combis",
    "link_documento": " con el objetivo de apoyar a concesionarios y garantizar la continuidad del servicio.",
    "link_portal": "",
    "fuente_verificada": "https://congresoags.gob.mx/agenda_legislativa/iniciativas",
    "notas": "No",
    "estado": "Aguascalientes"
  },
  {
    "id": "AGS-2025-003",
    "fecha": "2025-07-01",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "\"Promover que los vehículos particulares cuenten con seguro obligatorio por ley para cubrir gastos catastróficos\"",
    "resumen": "Iniciativa para hacer obligatorio el seguro vehicular en el Estado de Aguascalientes para todos los vehículos particulares. Presentada por el presidente de la Comisión de Transporte. Busca proteger a la ciudadanía ante gastos catastróficos derivados de accidentes de tránsito donde el responsable no tiene cobertura.",
    "link_documento": "",
    "link_portal": "https://congresoags.gob.mx/agenda_legislativa/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: transporte | Presentada por diputado Humberto Montero de Alba. Indicada como futura iniciativa en julio 2025; sin dictamen confirmado a la fecha de consulta.",
    "estado": "Aguascalientes"
  },
  {
    "id": "AGS-2025-001",
    "fecha": "2025-06-01",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ELEC",
    "subtema_secundario": "",
    "extracto": "\"Reconocer, regular y buscar garantizar el uso seguro, eficiente e inclusivo de los Vehículos de Movilidad Personal (VMP) —scooters eléctricos, monociclos, segways, ciclomotores de baja potencia— como alternativa de transporte sustentable\"",
    "resumen": "Dictamen acumulado aprobado con 24 votos en la 16ª sesión ordinaria de la LXVI Legislatura. Regula los Vehículos de Movilidad Personal: prohíbe su uso a menores de 16 años",
    "link_documento": " fija velocidad máxima de 25 km/h",
    "link_portal": " exige casco y lentes de protección",
    "fuente_verificada": " y permite circulación en ciclovías. Es el primer marco normativo explícito para este tipo de vehículos en el estado.",
    "notas": "https://congresoags.gob.mx/LegislativeAgenda/Download?id=15084",
    "estado": "Aguascalientes"
  },
  {
    "id": "AGS-2025-002",
    "fecha": "2025-03-01",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "MOV_TP",
    "extracto": "\"Se prohíbe a los conductores de vehículos públicos y privados manejar con mascotas en brazos; se obliga encender luces interiores durante servicios nocturnos en taxis y plataformas; se ratifica límite de 6 años de antigüedad máxima para vehículos en servicios digitales\"",
    "resumen": "Reforma a la Ley de Movilidad que fortalece la seguridad vial con tres medidas: prohibición de conducir con mascotas en brazos (riesgo de distracción)",
    "link_documento": " iluminación interior obligatoria en taxis nocturnos",
    "link_portal": " y tope de 6 años de antigüedad para vehículos de plataformas digitales. Presentada por la presidenta de la Comisión de Movilidad Sustentable y Transporte.",
    "fuente_verificada": "",
    "notas": "https://congresoags.gob.mx/agenda_legislativa/iniciativas",
    "estado": "Aguascalientes"
  }
];

const SUBTEMAS = {
  "ENE_GEN": "Generación y transición energética",
  "ENE_REG": "Marco regulatorio energético",
  "ENE_TAR": "Tarifas, subsidios y cortes de suministro",
  "ENE_HC": "Hidrocarburos, gas y combustibles",
  "ENE_EF": "Eficiencia energética y alumbrado",
  "MOV_SEG": "Seguridad vial",
  "MOV_INF": "Infraestructura vial",
  "MOV_ACT": "Movilidad activa",
  "MOV_TP": "Transporte público y concesiones",
  "MOV_ELEC": "Electromovilidad y vehículos eléctricos"
};
