const DATA = [
  {
    "id": "QROO-2026-009",
    "fecha": "2026-03-19",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Por el que se reforman y adicionan diversas disposiciones de la Ley Orgánica de la Administración Pública del Estado de Quintana Roo; por el que se reforman y derogan diversas disposiciones de la Ley de Movilidad del Estado de Quintana Roo.",
    "resumen": "Decreto aprobado de la más reciente reestructuración del ejecutivo que afecta la Ley de Movilidad. Actualiza la estructura orgánica del gobierno en materia de movilidad y transporte.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/decretos/DEC-XVIII-20260319.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/486",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: movilidad",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2026-010",
    "fecha": "2026-03-19",
    "tipo_acto": "Minuta",
    "estatus": "Ratificada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Minuta de Decreto por el que se reforman y adicionan diversas disposiciones de la Ley Orgánica de la Administración Pública del Estado de Quintana Roo; por el que se reforman y derogan diversas disposiciones de la Ley de Movilidad del Estado de Quintana Roo.",
    "resumen": "Minuta del decreto de reestructuración del ejecutivo con modificaciones a la Ley de Movilidad.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/minutas/MIN-XVIII-20260319.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/486",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Ratificada | Término búsqueda: movilidad",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2026-008",
    "fecha": "2026-03-18",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobado en comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Dictamen con Proyecto de Decreto que reforma y adiciona diversas disposiciones de la Ley Orgánica de la Administración Pública del Estado de Quintana Roo; y que reforma y deroga diversas disposiciones de la Ley de Movilidad del Estado de Quintana Roo.",
    "resumen": "Dictamen de comisión aprobando nueva reestructuración del ejecutivo estatal que incluye modificaciones a la Ley de Movilidad. Complementa las reformas estructurales del primer trimestre de 2026.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/dictamenes/DI-20260318.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/482",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado en comisión | Término búsqueda: movilidad",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2026-007",
    "fecha": "2026-03-13",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Publicado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa con Proyecto de Decreto por el que se adiciona un párrafo tercero al artículo 98 y se reforman los artículos 99 y 100 todos de la Ley de Movilidad del Estado de Quintana Roo.",
    "resumen": "Reforma a los artículos 98-100 de la Ley de Movilidad, que regulan las concesiones de transporte de personas. Modifica los requisitos y condiciones para la operación del transporte público.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/iniciativas/INI-XVIII-20260313.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/489",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: movilidad | Arts. 98-100 Ley de Movilidad: concesiones y autorización del transporte público de personas",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2026-005",
    "fecha": "2026-03-10",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Por el que se reforman, adicionan y derogan diversas disposiciones de la Ley de Movilidad del Estado de Quintana Roo; la Ley de los Municipios del Estado de Quintana Roo; y la Ley de Seguridad Ciudadana del Estado de Quintana Roo.",
    "resumen": "Decreto aprobado de la reforma integral del marco de movilidad y seguridad ciudadana. Unifica la regulación de movilidad, la competencia municipal y la seguridad en un solo decreto. Reforma de mayor alcance normativo del periodo.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/decretos/DEC-XVIII-20260310.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/477",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: movilidad",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2026-006",
    "fecha": "2026-03-10",
    "tipo_acto": "Minuta",
    "estatus": "Ratificada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Minuta de Decreto por el que se reforman, adicionan y derogan diversas disposiciones de la Ley de Movilidad del Estado de Quintana Roo; la Ley de los Municipios del Estado de Quintana Roo; y la Ley de Seguridad Ciudadana del Estado de Quintana Roo.",
    "resumen": "Minuta del decreto de reforma integral movilidad-municipios-seguridad ciudadana. Documenta la fase final del proceso legislativo de la reforma.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/minutas/MIN-XVIII-20260310.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/477",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Ratificada | Término búsqueda: movilidad",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2026-003",
    "fecha": "2026-03-03",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobado en comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Dictamen con Proyecto de Decreto que reforma, adiciona y deroga diversas disposiciones de la Ley de Movilidad del Estado de Quintana Roo; la Ley de los Municipios del Estado de Quintana Roo; y la Ley de Seguridad Ciudadana del Estado de Quintana Roo.",
    "resumen": "Dictamen de comisión que aprueba la reforma integral a tres leyes: Movilidad, Municipios y Seguridad Ciudadana. Resuelve favorablemente las iniciativas del ejecutivo sobre la política integral de movilidad y seguridad.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/dictamenes/DI-20260303T094024.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/474",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado en comisión | Término búsqueda: movilidad",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2026-001",
    "fecha": "2026-02-26",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Publicado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa con Proyecto de Decreto por el que se adiciona un tercer párrafo al artículo 19 de la Constitución Política del Estado Libre y Soberano de Quintana Roo, en materia de movilidad; presentada por la Gobernadora María Elena H. Lezama Espinosa.",
    "resumen": "La Gobernadora del Estado propone elevar la movilidad a rango constitucional, añadiendo un párrafo al artículo 19 de la Constitución estatal. Establece el derecho a la movilidad como garantía constitucional en Quintana Roo.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/iniciativas/INI-XVIII-20260226-CONST.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/472",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: movilidad | Iniciativa del ejecutivo estatal; reforma constitucional de alto impacto normativo",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2026-002",
    "fecha": "2026-02-26",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Publicado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Iniciativa con Proyecto de Decreto que reforma, adiciona y deroga diversas disposiciones de la Ley de Movilidad del Estado de Quintana Roo; la Ley de los Municipios del Estado de Quintana Roo; y la Ley de Seguridad Ciudadana del Estado de Quintana Roo; presentada por la Gobernadora.",
    "resumen": "La Gobernadora presentó una reforma integral que vincula movilidad, gobernanza municipal y seguridad ciudadana. Modifica tres leyes simultáneamente para articular la política de movilidad con la seguridad pública.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/iniciativas/INI-XVIII-20260226-MOV.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/472",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: movilidad | Iniciativa del ejecutivo; reforma estructural de movilidad + seguridad ciudadana",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2026-004",
    "fecha": "2026-02-26",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Publicado",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto que reforma diversas disposiciones de la Ley de Movilidad del Estado de Quintana Roo, la Ley de Asentamientos Humanos, Ordenamiento Territorial y Desarrollo Urbano del Estado de Quintana Roo.",
    "resumen": "Iniciativa que vincula la Ley de Movilidad con la ley de ordenamiento territorial. Busca integrar la planificación de infraestructura vial con el desarrollo urbano sostenible del estado.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/iniciativas/INI-XVIII-20260226-LOTA.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/474",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: movilidad | Subtema principal MOV_INF por efecto en infraestructura vial y planeación urbana",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-020",
    "fecha": "2025-12-15",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobado en comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Dictamen con proyecto de Decreto que reforma, adiciona y deroga diversas disposiciones de la Ley Orgánica de la Administración Pública del Estado de Quintana Roo; la Ley de Derechos del Estado de Quintana Roo y la Ley de Movilidad del Estado de Quintana Roo.",
    "resumen": "Dictamen de comisión de la segunda reforma estructural que incluye la Ley de Movilidad. Consolidación del proceso de reestructuración de la administración pública estatal.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/dictamenes/DI-20251215-LOAPQ-MOV.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/446",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado en comisión | Término búsqueda: movilidad",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-021",
    "fecha": "2025-12-15",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Por el que se reforman, adicionan y derogan diversas disposiciones de la Ley Orgánica de la Administración Pública del Estado de Quintana Roo; la Ley de Derechos del Estado de Quintana Roo; la Ley de Movilidad del Estado de Quintana Roo.",
    "resumen": "Decreto aprobado de reforma estructural del ejecutivo estatal. Modifica la organización del gobierno, reasignando atribuciones de movilidad y transporte en la estructura de la administración pública.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/decretos/DEC-XVIII-20251215-LOAPQ-MOV.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/453",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: movilidad",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-022",
    "fecha": "2025-12-15",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Por el que se reforman, derogan y adicionan diversas disposiciones de la Ley Orgánica de la Administración Pública, la Ley del Servicio de Administración Tributaria y la Ley de Movilidad del Estado de Quintana Roo.",
    "resumen": "Segundo decreto de la reforma estructural del gobierno. Modifica además la Ley del SAT estatal en coordinación con los cambios a la administración pública y la Ley de Movilidad.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/decretos/DEC-XVIII-20251215-LOAPQ-MOV-II.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/453",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: movilidad",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-023",
    "fecha": "2025-12-15",
    "tipo_acto": "Minuta",
    "estatus": "Ratificada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Minuta de Decreto por el que se reforman, adicionan y derogan diversas disposiciones de la Ley Orgánica de la Administración Pública del Estado de Quintana Roo; la Ley de Derechos del Estado de Quintana Roo; la Ley de Movilidad.",
    "resumen": "Minuta del primer decreto de reestructuración del ejecutivo estatal que modifica la Ley de Movilidad.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/minutas/MIN-XVIII-20251215-LOAPQ-I.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/453",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Ratificada | Término búsqueda: movilidad",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-024",
    "fecha": "2025-12-15",
    "tipo_acto": "Minuta",
    "estatus": "Ratificada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Minuta de Decreto por el que se reforman, derogan y adicionan diversas disposiciones de la Ley Orgánica de la Administración Pública, la Ley del Servicio de Administración Tributaria y la Ley de Movilidad.",
    "resumen": "Minuta del segundo decreto de reestructuración del ejecutivo estatal, incluyendo cambios a la Ley de Movilidad y la Ley del SAT.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/minutas/MIN-XVIII-20251215-LOAPQ-II.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/453",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Ratificada | Término búsqueda: movilidad",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-019",
    "fecha": "2025-12-11",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Publicado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa con Proyecto de Decreto que reforma, adiciona y deroga diversas disposiciones de la Ley Orgánica de la Administración Pública del Estado de Quintana Roo; la Ley de Derechos del Estado de Quintana Roo; la Ley de Movilidad del Estado de Quintana Roo.",
    "resumen": "Segunda iniciativa de reestructuración del ejecutivo que modifica LOAPQ, Ley de Derechos y Ley de Movilidad. Parte del proceso legislativo de reorganización del gobierno estatal.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/iniciativas/INI-XVIII-20251211.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/446",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: movilidad",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-018",
    "fecha": "2025-12-10",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobado en comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Dictamen con Proyecto de Decreto que reforma, deroga y adiciona diversas disposiciones de la Ley Orgánica de la Administración Pública, la Ley del Servicio de Administración Tributaria y la Ley de Movilidad del Estado de Quintana Roo.",
    "resumen": "Dictamen de comisión que aprueba la reestructuración orgánica del ejecutivo estatal, incluyendo modificaciones a la Ley de Movilidad. Avanza el proceso para una reforma estructural del gobierno de Quintana Roo.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/dictamenes/DI-20251210-LOAPQ-MOV.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/446",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado en comisión | Término búsqueda: movilidad",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-017",
    "fecha": "2025-12-05",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Publicado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa Ciudadana que reforma el artículo 236 del Capítulo Segundo denominado \"De las Sanciones de Tránsito y Vialidad\" de la Ley de Movilidad del Estado de Quintana Roo.",
    "resumen": "Iniciativa ciudadana que propone modificar el artículo 236 de la Ley de Movilidad, específicamente el capítulo de sanciones de tránsito y vialidad. Busca ajustar el sistema de multas o infracciones viales.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/iniciativas/INI-XVIII-20251205.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/487",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: tránsito | Iniciativa ciudadana; subtema MOV_SEG por Capítulo de Sanciones de Tránsito y Vialidad",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-016",
    "fecha": "2025-11-20",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Publicado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa con Proyecto de Decreto que reforma, adiciona y deroga diversas disposiciones de la Ley Orgánica de la Administración Pública; de la Ley del Servicio de Administración Tributaria y la Ley de Movilidad del Estado de Quintana Roo.",
    "resumen": "Reforma estructural que reestructura simultáneamente tres leyes: la Ley Orgánica, la Ley del SAT estatal y la Ley de Movilidad. Implica cambios organizacionales en el gobierno que afectan la estructura de movilidad.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/iniciativas/INI-XVIII-20251120.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/438",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: movilidad | Reforma de reestructuración del ejecutivo que incluye cambios a la Ley de Movilidad",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-015",
    "fecha": "2025-11-12",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Publicado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa por la que se reforman y adicionan diversas disposiciones de la Ley de Movilidad del Estado de Quintana Roo; presentada por el Diputado Filiberto Martínez Méndez, Presidente de la Comisión de Movilidad.",
    "resumen": "Reforma integral a diversas disposiciones de la Ley de Movilidad presentada por el presidente de la Comisión de Movilidad. Segunda iniciativa de reforma general de la misma autoría en el periodo.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/iniciativas/INI-XVIII-20251112.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/463",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: movilidad",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-014",
    "fecha": "2025-09-09",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Publicado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa por la que se reforman la fracción XXIII del artículo 5 y el artículo 171, ambos de la Ley de Movilidad del Estado de Quintana Roo; presentada por el Diputado Filiberto Martínez Méndez, Presidente de la Comisión de Movilidad.",
    "resumen": "Reforma a la fracción XXIII del artículo 5 (definiciones) y al artículo 171 (infracciones/sanciones) de la Ley de Movilidad. Actualiza definiciones y el catálogo de infracciones administrativas.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/iniciativas/INI-XVIII-20250909.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/409",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: movilidad | Art. 171: probablemente catálogo de infracciones o sanciones; MOV_REG por ser marco general",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-013",
    "fecha": "2025-05-15",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Publicado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por la que se reforma la Ley de Movilidad del Estado de Quintana Roo; presentada por el Diputado Wilbert Alberto Batún Chulim, Presidente de la Comisión de Movilidad.",
    "resumen": "Iniciativa de reforma general a la Ley de Movilidad presentada por el presidente de la Comisión de Movilidad. Actualización del marco normativo de movilidad estatal sin especificar artículos en el epígrafe.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/iniciativas/INI-XVIII-20250515.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/362",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: movilidad",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-012",
    "fecha": "2025-03-31",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Publicado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Iniciativa de Decreto que modifica la fracción XLI del artículo 5; el tercer párrafo del artículo 172; los artículos 173 y 174; el último párrafo del artículo 176; la fracción I y fracción VII del artículo 188 Quáter; y el inciso a) de la fracción VI del artículo 197 de la Ley de Movilidad del Estado de Quintana Roo.",
    "resumen": "Reforma a múltiples artículos de la Ley de Movilidad que actualiza definiciones (art. 5), el capítulo de infracciones (arts. 172-176), las disposiciones del órgano técnico (art. 188 Quáter) y el procedimiento administrativo (art. 197).",
    "link_documento": "https://documentos.congresoqroo.gob.mx/iniciativas/INI-XVIII-20250331.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/344",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: movilidad | Subtema corregido: MOV_REG principal + MOV_SEG por reformas al capítulo de infracciones",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-001",
    "fecha": "2025-02-17",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Publicado",
    "macrotema": "Energía",
    "subtema": "ENE_EF",
    "subtema_secundario": "ENE_GEN",
    "extracto": "Expide la Ley para la Implementación de Energías Limpias y Renovables en los Edificios Públicos del Estado de Quintana Roo y sus Municipios; presentada por la Diputada Andrea del Rosario González Loría.",
    "resumen": "Iniciativa para expedir una nueva ley que obligue a edificios públicos estatales y municipales a implementar energías limpias y renovables. Establece el marco normativo para la transición energética en el sector público del estado.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/iniciativas/INI-XVIII-20250217-094024.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/328",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: energía | Nueva ley; subtema secundario ENE_GEN por generar marco de generación renovable",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-011",
    "fecha": "2025-02-10",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Publicado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa con Proyecto de Decreto por el que se deroga el artículo 218 bis de la Ley de Movilidad del Estado de Quintana Roo.",
    "resumen": "Iniciativa para derogar el artículo 218 bis de la Ley de Movilidad, que probablemente regula algún aspecto específico de los servicios de transporte por aplicación digital o transporte de renta. Simplificación normativa del capítulo de transporte.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/iniciativas/INI-XVIII-20250210.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/322",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: movilidad | Artículo 218 bis: probablemente regula plataformas digitales de transporte",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-010",
    "fecha": "2025-02-04",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Publicado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Acuerdo No. 64 del H. Congreso de Michoacán que exhorta a los Congresos locales a instalar \"Puntos Naranja\" para prevenir violencia de género, garantizando el derecho a la movilidad y tránsito seguro de mujeres y niñas.",
    "resumen": "El Congreso de Michoacán exhortó a las legislaturas estatales a establecer Puntos Naranja para la seguridad en movilidad de mujeres. Conecta la política de seguridad vial con perspectiva de género.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/correspondencia/CORR-XVIII-20250204-MICH.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/319",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: tránsito | Subtema MOV_SEG: enfoque en seguridad del tránsito con perspectiva de género",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-006",
    "fecha": "2025-01-30",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Por el que se reforman y adicionan diversas disposiciones del Código Penal para el Estado Libre y Soberano de Quintana Roo; y por el que se reforman y adicionan diversas disposiciones de la Ley de Movilidad del Estado de Quintana Roo.",
    "resumen": "Decreto aprobado que modifica el Código Penal y la Ley de Movilidad para fortalecer el marco sancionador de conductas viales graves. Establece tipos penales y agrava las consecuencias de infracciones de tránsito severas.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/decretos/DEC-XVIII-20250130-CP-MOV.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/318",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: movilidad",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-007",
    "fecha": "2025-01-30",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Por el que la H. XVIII Legislatura del Estado de Quintana Roo aprueba el otorgamiento de concesiones para la prestación del servicio público de transporte de renta de toda clase de vehículos para operar en el Estado de Quintana Roo.",
    "resumen": "Decreto aprobado que autoriza nuevas concesiones para transporte de renta en todo el estado, incluyendo plataformas digitales de movilidad. Define el universo de operadores y tipos de vehículos habilitados.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/decretos/DEC-XVIII-20250130-CONCESIONES.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/318",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: transporte",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-008",
    "fecha": "2025-01-30",
    "tipo_acto": "Minuta",
    "estatus": "Ratificada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Minuta de Decreto por el que se reforman y adicionan diversas disposiciones del Código Penal para el Estado Libre y Soberano de Quintana Roo y por el que se reforman y adicionan diversas disposiciones de la Ley de Movilidad del Estado de Quintana Roo.",
    "resumen": "Minuta del decreto que reforma Código Penal y Ley de Movilidad. Proceso de coordinación federación-estado en materia de tipificación de conductas viales.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/minutas/MIN-XVIII-20250130-CP-MOV.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/318",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Ratificada | Término búsqueda: movilidad",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-009",
    "fecha": "2025-01-30",
    "tipo_acto": "Minuta",
    "estatus": "Ratificada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Minuta de Decreto por el que la H. XVIII Legislatura del Estado de Quintana Roo aprueba el otorgamiento de concesiones para la prestación del servicio público de transporte de renta.",
    "resumen": "Minuta del decreto de concesiones de transporte de renta. Documenta la decisión legislativa formal sobre habilitación de operadores de transporte en el estado.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/minutas/MIN-XVIII-20250130-CONCESIONES.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/318",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Ratificada | Término búsqueda: transporte",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-004",
    "fecha": "2025-01-28",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobado en comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Dictamen con Proyecto de Decreto que reforma y adiciona diversas disposiciones del Código Penal para el Estado Libre y Soberano de Quintana Roo y la Ley de Movilidad del Estado de Quintana Roo.",
    "resumen": "Dictamen de comisión aprobando la reforma al Código Penal y Ley de Movilidad para tipificar conductas viales como delitos o agravar sanciones. Resolución de comisión que avanza el proceso legislativo.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/dictamenes/DI-20250128-CP-MOV.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/317",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado en comisión | Término búsqueda: movilidad",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-005",
    "fecha": "2025-01-28",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobado en comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Dictamen con Proyecto de Decreto por el que la H. XVIII Legislatura del Estado de Quintana Roo aprueba el otorgamiento de concesiones para la prestación del servicio público de transporte de renta de toda clase de vehículos para operar en el Estado.",
    "resumen": "Dictamen de comisión que aprueba el otorgamiento de concesiones para transporte de renta (incluyendo taxis, plataformas digitales y todos los tipos de vehículos) para operar en todo el estado de Quintana Roo.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/dictamenes/DI-20250128-CONCESIONES.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/317",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado en comisión | Término búsqueda: transporte | Subtema MOV_TP: concesiones de servicio público de transporte; efecto jurídico principal en operadores",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-002",
    "fecha": "2025-01-27",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Publicado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Solicitud de revisión y en su caso aprobación del Dictamen Resolutivo IMOVEQROO/DG/2707/2024, emitido por el Director General del Instituto de Movilidad, bajo los términos previstos en las disposiciones de la Ley de Movilidad del Estado.",
    "resumen": "El Director General del IMOVEQROO solicitó al Congreso la revisión y aprobación de un dictamen resolutivo sobre movilidad (folio 2707/2024). Ejercicio del control legislativo sobre el órgano regulador de movilidad estatal.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/correspondencia/CORR-XVIII-20250127-IMOV.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/316",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: movilidad | Mecanismo de control legislativo del IMOVEQROO",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2025-003",
    "fecha": "2025-01-27",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Publicado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "MOV_TP",
    "extracto": "Iniciativa con Proyecto de Decreto que reforma y adiciona diversas disposiciones del Código Penal para el Estado Libre y Soberano de Quintana Roo y de la Ley de Movilidad del Estado de Quintana Roo.",
    "resumen": "Iniciativa que modifica simultáneamente el Código Penal y la Ley de Movilidad para fortalecer las sanciones vinculadas a infracciones de tránsito con consecuencias penales. Busca armonizar el marco penal con la regulación de movilidad.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/iniciativas/INI-XVIII-20250127.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/316",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: movilidad | Subtema corregido: MOV_SEG por efecto jurídico principal en sanciones viales",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2024-012",
    "fecha": "2024-12-10",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Publicado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Oficio remitido por la Consejería Jurídica del Municipio de Tulum mediante el cual presenta opinión sobre concesiones de transporte público en el municipio.",
    "resumen": "La Consejería Jurídica del Municipio de Tulum remitió oficio al Congreso relacionado con asuntos de concesiones de transporte público local. Se trata de gestión interinstitucional sobre regulación del transporte en Tulum.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/correspondencia/CORR-XVIII-20241210-TUL-01.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/314",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: transporte",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2024-013",
    "fecha": "2024-12-10",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Publicado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Segundo oficio remitido por la Consejería Jurídica del Municipio de Tulum sobre asuntos de concesiones de transporte público.",
    "resumen": "Segundo oficio de la Consejería Jurídica de Tulum al Congreso del Estado sobre regulación de transporte público en el municipio. Parte de la gestión sobre la política de concesiones de movilidad en Tulum.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/correspondencia/CORR-XVIII-20241210-TUL-02.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/314",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: transporte | Duplicado temático del registro anterior; misma fuente diferente trámite",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2024-011",
    "fecha": "2024-11-25",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Publicado",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Oficio remitido por el H. Congreso del Estado de Morelos comunicando su voto positivo y aprobatorio a la Minuta de reforma al artículo 28 de la CPEUM en materia de vías y transporte ferroviario.",
    "resumen": "El Congreso de Morelos informó su voto positivo para la ratificación de la reforma constitucional sobre transporte ferroviario. Correspondencia relacionada al proceso federal de infraestructura ferroviaria.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/correspondencia/CORR-XVIII-20241125-MOR.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/298",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: transporte",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2024-001",
    "fecha": "2024-11-12",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Publicado",
    "macrotema": "Energía",
    "subtema": "ENE_REG",
    "subtema_secundario": "",
    "extracto": "Acuerdo remitido por el H. Congreso de Chihuahua que exhorta a las 32 Legislaturas a analizar la Reforma Energética y promover políticas de energías renovables y sostenibilidad.",
    "resumen": "El Congreso de Chihuahua exhortó a las legislaturas estatales a analizar la Reforma Energética aprobada por el Senado y a promover energías renovables. El Congreso de Quintana Roo lo recibió como correspondencia para su información y posible acuerdo.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/acuerdos/ACU-XVIII-20241112-094024.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/290",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: energía | Origen: exhort de Chihuahua; efecto local: recepción informativa",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2024-010",
    "fecha": "2024-11-12",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_ACT",
    "extracto": "Acuerdo de Urgente y Obvia resolución por el que la XVIII Legislatura exhorta al Director General del IMOVEQROO a ejecutar acciones para la aplicación de la normativa en favor de los derechos de personas con discapacidad en relación al transporte público inclusivo.",
    "resumen": "La Legislatura exhortó al IMOVEQROO a garantizar el acceso al transporte público para personas con discapacidad, conforme al artículo 13 de la Ley de Movilidad y los artículos 33-35 de la Ley para el Desarrollo e Inclusión de las personas con discapacidad.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/acuerdos/ACU-XVIII-20241112-MOV.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/290",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: transporte | Acuerdo interno; exhort al ejecutivo estatal en materia de accesibilidad",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2024-007",
    "fecha": "2024-10-22",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Publicado",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Puntos de Acuerdos remitidos por el H. Congreso de Tamaulipas comunicando voto positivo a la Minuta de Decreto que reforma el artículo 28 de la CPEUM en materia de vías y transporte ferroviario.",
    "resumen": "El Congreso de Tamaulipas informó su voto positivo para ratificar la reforma al artículo 28 constitucional sobre transporte ferroviario. Se incluye como parte del proceso de ratificación de la reforma federal de infraestructura ferroviaria.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/correspondencia/CORR-XVIII-20241022-TAM.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/279",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: transporte | Correspondencia informativa del proceso de ratificación federal",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2024-008",
    "fecha": "2024-10-22",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Por el que se reforma el párrafo cuarto y se adiciona un párrafo quinto al artículo 28 de la Constitución Política de los Estados Unidos Mexicanos, en materia de vías y transporte ferroviario.",
    "resumen": "Decreto de ratificación por parte del Congreso de Quintana Roo de la reforma federal al artículo 28 constitucional en materia de vías y transporte ferroviario. Establece el régimen público/concesionado del ferrocarril.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/decretos/DEC-XVIII-20241022-CPEUM.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/279",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: transporte",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2024-009",
    "fecha": "2024-10-22",
    "tipo_acto": "Minuta",
    "estatus": "Ratificada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Minuta de Decreto por la que se reforma el párrafo cuarto y se adiciona un párrafo quinto al artículo 28 de la CPEUM, en materia de vías y transporte ferroviario.",
    "resumen": "Minuta de ratificación del decreto federal sobre transporte ferroviario. Quintana Roo formalizó su voto de ratificación a la reforma constitucional sobre el régimen ferroviario nacional.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/minutas/MIN-XVIII-20241022-CPEUM.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/279",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Ratificada | Término búsqueda: transporte",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2024-006",
    "fecha": "2024-10-18",
    "tipo_acto": "Minuta",
    "estatus": "Enviada a ratificación",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Minuta con Proyecto de Decreto por el que se reforma el párrafo cuarto y se adiciona un párrafo quinto al artículo 28 de la Constitución Política de los Estados Unidos Mexicanos, en materia de Vías y Transporte Ferroviario; remitida por la Cámara de Senadores.",
    "resumen": "Minuta enviada por el Senado que modifica el artículo 28 constitucional para establecer el régimen jurídico de las vías y el transporte ferroviario en México. Quintana Roo la recibió para su ratificación.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/minutas/MIN-XVIII-20241018.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/278",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Enviada a ratificación | Término búsqueda: transporte | Reforma constitucional federal que requiere ratificación de legislaturas locales",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2024-005",
    "fecha": "2024-10-15",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Publicado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa de decreto que reforma la denominación del Capítulo VII del Título Segundo para quedar \"Movilidad Personal y Transporte\" y reforma los artículos 33, 34 y 35 de la Ley de Movilidad del Estado de Quintana Roo.",
    "resumen": "Iniciativa para renombrar y reformar el capítulo de transporte personal en la Ley de Movilidad, actualizando artículos 33-35 relativos a concesiones y operación del transporte de personas.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/iniciativas/INI-XVIII-20241015.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/275",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: transporte",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2024-002",
    "fecha": "2024-09-23",
    "tipo_acto": "Dictamen",
    "estatus": "Publicado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Dictamen con Proyecto de Decreto que reforma diversas disposiciones de la Ley de las Entidades de la Administración Pública Paraestatal del Estado de Quintana Roo y que reforma y adiciona diversas disposiciones de la Ley de Movilidad del Estado de Quintana Roo.",
    "resumen": "Dictamen de comisión que aprueba reforma simultánea a la Ley de Entidades Paraestatales y a la Ley de Movilidad del Estado. Modifica el marco regulatorio del Instituto de Movilidad (IMOVEQROO) como entidad paraestatal.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/dictamenes/DI-20240923T181156.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/265",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: movilidad | Reforma estructural institucional del IMOVEQROO",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2024-003",
    "fecha": "2024-09-23",
    "tipo_acto": "Minuta",
    "estatus": "Publicado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Minuta de decreto por la que se reforman diversas disposiciones de la Ley de las Entidades de la Administración Pública Paraestatal del Estado de Quintana Roo y la Ley de Movilidad del Estado de Quintana Roo.",
    "resumen": "Minuta de decreto que reforma la Ley de Entidades Paraestatales y la Ley de Movilidad. Establece el fundamento legislativo del IMOVEQROO dentro del esquema de la administración pública paraestatal.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/minutas/MIN-XVIII-20240923.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/270",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Publicado | Término búsqueda: movilidad | Minuta federal del mismo decreto",
    "estado": "Quintana Roo"
  },
  {
    "id": "QROO-2024-004",
    "fecha": "2024-09-23",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Por el que se reforman diversas disposiciones de la Ley de las Entidades de la Administración Pública Paraestatal del Estado de Quintana Roo y se reforman y adicionan diversas disposiciones de la Ley de Movilidad del Estado de Quintana Roo.",
    "resumen": "Decreto aprobado que modifica la estructura jurídica del IMOVEQROO y actualiza la Ley de Movilidad en materia de gobernanza institucional del transporte estatal.",
    "link_documento": "https://documentos.congresoqroo.gob.mx/decretos/DEC-XVIII-20240923.pdf",
    "link_portal": "https://gacetaparlamentaria.congresoqroo.gob.mx/gaceta/270",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: movilidad",
    "estado": "Quintana Roo"
  }
];

const SUBTEMAS = {
  "ENE_GEN": "Generación y transición energética",
  "ENE_REG": "Marco regulatorio energético",
  "ENE_TAR": "Tarifas, subsidios y cortes de suministro",
  "ENE_HC": "Hidrocarburos, gas y combustibles",
  "ENE_EF": "Eficiencia energética y alumbrado",
  "MOV_SEG": "Seguridad vial",
  "MOV_INF": "Infraestructura vial",
  "MOV_ACT": "Movilidad activa",
  "MOV_TP": "Transporte público y concesiones",
  "MOV_ELEC": "Electromovilidad y vehículos eléctricos"
};
