const DATA = [
  {
    "id": "GTO-2026-001",
    "fecha": "2026-01-01",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Punto de acuerdo que exhorta a la SICT federal a evaluar e implementar una solución integral de infraestructura para resolver las interrupciones sistemáticas al flujo vehicular y peatonal en la zona Santa Rosa Plan de Ayala, León, causadas por el cruce ferroviario, y a establecer medidas urgentes de señalética, control y seguridad vial en dicho cruce.",
    "resumen": "El Congreso del Estado aprobó el dictamen de punto de acuerdo en materia de transporte público para exhortar a la Secretaría de Infraestructura, Comunicaciones y Transportes (SICT) a resolver el problema de seguridad vial generado por el cruce ferroviario de Santa Rosa Plan de Ayala en León, que interrumpe sistemáticamente el flujo vehicular y peatonal de la zona. Solicita solución de infraestructura e instalación urgente de señalética.",
    "link_documento": "",
    "link_portal": "https://www.congresogto.gob.mx/comunicados/avalan-dictamen-de-punto-de-acuerdo-en-materia-de-transporte-publico",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado (dictamen avalado) | Término búsqueda: transporte | Fecha aproximada (Q1 2026) | Subtema corregido: MOV_TP→MOV_INF (el efecto jurídico es solución de infraestructura vial en cruce ferroviario, no regulación de transporte público)",
    "estado": "Guanajuato"
  },
  {
    "id": "GTO-2025-003",
    "fecha": "2025-10-01",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En análisis",
    "macrotema": "Movilidad",
    "subtema": "MOV_ELEC",
    "subtema_secundario": "",
    "extracto": "Iniciativa del Grupo Parlamentario del PAN y representación parlamentaria del PRD para reformar y adicionar la Ley de Movilidad del Estado de Guanajuato, incorporando dos nuevas categorías de vehículos de propulsión eléctrica: micromovilidad eléctrica (hasta 25 km/h: scooters, bicicletas, patinetas eléctricas) y vehículos de alta velocidad eléctrica (más de 25 km/h, equiparados a motocicletas). Prevé registro, plaqueo y condiciones de seguridad vial para cada categoría.",
    "resumen": "Iniciativa PAN-PRD para que Guanajuato cuente con un marco legal pionero que clasifique, registre y controle los vehículos de propulsión eléctrica ligeros. En octubre de 2025 se celebró el Foro de Consulta 'Por un Guanajuato con movilidad sostenible y moderna' como parte del proceso legislativo. En marzo de 2026 la iniciativa continuaba bajo análisis, con aprobación esperada en los próximos meses según fuentes de prensa.",
    "link_documento": "",
    "link_portal": "https://www.congresogto.gob.mx/comunicados/proponen-regular-los-vehiculos-de-propulsion-electrica",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En análisis | Término búsqueda: eléctrica | Fecha aproximada (foro oct 2025; iniciativa presentada may 2025) | A 2026-03-17 aún sin dictamen aprobado",
    "estado": "Guanajuato"
  },
  {
    "id": "GTO-2025-002",
    "fecha": "2025-06-26",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada, vigente 2026-01-01",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "El Pleno del Congreso aprobó reformas a la Ley de Movilidad del Estado para reforzar la seguridad de motociclistas: uso obligatorio de cascos certificados homologados, elementos reflejantes en la indumentaria, aditamentos luminosos indispensables, prohibición de motocicletas para transporte sin ruta fija, regulación del traslado de menores, y creación del Padrón de Control Estatal de Motocicletas (CEM) como instrumento de prevención del delito.",
    "resumen": "Decreto aprobado el 26 de junio de 2025 con entrada en vigor el 1 de enero de 2026, que modifica artículos 16 bis, 33, 64 y 84 de la Ley de Movilidad, con adición de fracciones V ter y VIII al artículo 64. Establece estándares obligatorios de equipamiento de seguridad para motociclistas, crea el Padrón de Control Estatal de Motocicletas (CEM) y el Padrón de Comerciantes de Motocicletas para prevención del crimen. Guanajuato registra el 7% nacional de muertes por accidentes viales.",
    "link_documento": "",
    "link_portal": "https://www.congresogto.gob.mx/comunicados/congreso-avala-medidas-para-mejorar-la-movilidad-y-seguridad-de-usuarios-de-motocicletas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: movilidad | Vigencia 01-01-2026 conforme Art. Primero Transitorio del Decreto",
    "estado": "Guanajuato"
  },
  {
    "id": "GTO-2025-004",
    "fecha": "2025-06-01",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_ELEC",
    "subtema_secundario": "",
    "extracto": "Punto de acuerdo del Grupo Parlamentario del PAN y representación del PRD para exhortar a los municipios de León, Irapuato, Celaya, Salamanca, Guanajuato, Silao de la Victoria, San Francisco del Rincón, San Miguel de Allende, Pénjamo, Dolores Hidalgo, Valle de Santiago, San Luis de la Paz y Acámbaro a priorizar el desarrollo e instalación de infraestructura de carga para vehículos eléctricos e híbridos en zonas de alta concentración demográfica.",
    "resumen": "El Congreso aprobó exhortar a los 13 principales municipios del estado a instalar infraestructura de carga para vehículos eléctricos e híbridos, priorizando municipios con alto estrés hídrico y alta concentración de fuentes contaminantes. También se exhorta a los Poderes Ejecutivo y Judicial estatales a fortalecer infraestructura de carga en sus instalaciones públicas. Complementa la iniciativa de regulación de electromovilidad (GTO-2025-003).",
    "link_documento": "",
    "link_portal": "https://www.congresogto.gob.mx/comunicados/piden-a-municipios-instalen-infraestructura-para-cargar-vehiculos-electricos-e-implementen-soluciones-de-reuso-del-agua",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: eléctrica | Fecha aproximada (solo año disponible)",
    "estado": "Guanajuato"
  },
  {
    "id": "GTO-2025-001",
    "fecha": "2025-04-04",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Energía",
    "subtema": "ENE_REG",
    "subtema_secundario": "",
    "extracto": "Nueva Ley de la Agencia de Energía del Estado de Guanajuato que crea un organismo público descentralizado de la administración pública estatal, con personalidad jurídica, patrimonio propio y autonomía técnica, sectorizado a la Secretaría de Desarrollo Económico Sustentable, responsable de diseñar, coordinar y dar seguimiento a las políticas públicas en materia energética del estado.",
    "resumen": "Se aprobó la Ley de la Agencia de Energía del Estado de Guanajuato creando un organismo descentralizado con autonomía técnica para diseñar y coordinar la política energética estatal, alineada con compromisos nacionales e internacionales en sustentabilidad y cambio climático. La Agencia desarrollará la primera Estrategia Estatal de Transición Energética con metas a 2030. El gobierno estatal confirmó en abril de 2025 que estaría operativa en el segundo semestre de ese año.",
    "link_documento": "",
    "link_portal": "https://www.congresogto.gob.mx/leyes/78",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: energía | Fecha exacta de aprobación no disponible; se usa fecha de anuncio gubernamental (04-04-2025) como proxy",
    "estado": "Guanajuato"
  },
  {
    "id": "GTO-2024-002",
    "fecha": "2024-09-26",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "MOV_INF",
    "extracto": "El Congreso estableció el derecho humano a la movilidad y la seguridad vial en la Ley de Movilidad, adoptando el enfoque de sistemas seguros con respeto a los derechos humanos. Toda persona tiene derecho a la movilidad bajo condiciones de seguridad vial, accesibilidad, eficiencia, sustentabilidad, calidad, inclusión e igualdad.",
    "resumen": "Reforma que reconoce la movilidad como derecho humano en la Ley estatal y adopta el enfoque de sistemas seguros para la prevención de muertes y lesiones en el tránsito. Se reformaron también el Código Territorial y la Ley del Sistema de Seguridad Pública. Homologa el marco estatal con los compromisos de la Décima de Acción para la Seguridad Vial 2021-2030.",
    "link_documento": "",
    "link_portal": "https://www.congresogto.gob.mx/comunicados/aprueban-reformas-que-establecen-el-derecho-humano-a-la-movilidad-y-seguridad-vial",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: movilidad | Fecha aproximada (Sept 2024 según disposición transitoria)",
    "estado": "Guanajuato"
  },
  {
    "id": "GTO-2024-001",
    "fecha": "2024-07-05",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Reformas a la Ley de Movilidad del Estado de Guanajuato armonizadas con la Ley General de Movilidad y Seguridad Vial, incorporando calles completas, diseño universal, presupuesto para movilidad y seguridad vial, perspectiva de género y herramientas de accesibilidad para personas con discapacidad (guías táctiles, señalética, pantallas en paradas, semáforos sonoros).",
    "resumen": "Se reformó la Ley de Movilidad, el Código Territorial y la Ley del Sistema de Seguridad Pública para armonizarlos con la Ley General de Movilidad y Seguridad Vial. La reforma establece que la asignación presupuestal para vialidades incorpore criterios de calles completas y diseño universal. Integra perspectiva de género, movilidad de cuidados y herramientas tecnológicas de accesibilidad (pantallas en paradas, semáforos con audio, videos en LSM).",
    "link_documento": "",
    "link_portal": "https://www.congresogto.gob.mx/comunicados/aprueban-reformas-en-materia-de-movilidad",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: movilidad | Fecha aproximada (Fe de Erratas publicada 2024-07-05; reforma aprobada ~abril-mayo 2024)",
    "estado": "Guanajuato"
  },
  {
    "id": "GTO-2024-003",
    "fecha": "2024-01-01",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "MOV_INF",
    "extracto": "Iniciativa de la Dip. Desiree Ángel Rocha (Movimiento Ciudadano) para reformar la Ley de Movilidad y garantizar que las obras de infraestructura vial urbana y carretera prioricen a peatones, vehículos no motorizados y transporte público, bajo principios de calidad, conectividad, diseño universal, intersecciones seguras, señalización auto-explicativa y pacificación del tránsito.",
    "resumen": "Iniciativa de reforma a la Ley de Movilidad del Estado (Exp. 5950) que busca que toda obra de infraestructura vial deba priorizar, en orden, a peatones, ciclistas y transporte público antes que al vehículo particular. Incluye criterios de accesibilidad universal, prevención de la discriminación y señalización legible. A la fecha no se ha localizado dictamen aprobatorio.",
    "link_documento": "",
    "link_portal": "https://www.congresogto.gob.mx/comunicados/formulan-iniciativa-para-garantizar-infraestructura-vial-que-priorice-a-las-personas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: vialidad | Fecha aproximada (solo año disponible) | Subtema corregido: MOV_INF→MOV_ACT (efecto jurídico: mandato de prioridad a movilidad activa en diseño de infraestructura)",
    "estado": "Guanajuato"
  }
];

const SUBTEMAS = {
  "ENE_GEN": "Generación y transición energética",
  "ENE_REG": "Marco regulatorio energético",
  "ENE_TAR": "Tarifas, subsidios y cortes de suministro",
  "ENE_HC": "Hidrocarburos, gas y combustibles",
  "ENE_EF": "Eficiencia energética y alumbrado",
  "MOV_SEG": "Seguridad vial",
  "MOV_INF": "Infraestructura vial",
  "MOV_ACT": "Movilidad activa",
  "MOV_TP": "Transporte público y concesiones",
  "MOV_ELEC": "Electromovilidad y vehículos eléctricos"
};
