const DATA = [
  {
    "id": "TAB-2026-001",
    "fecha": "2026-03-30",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_REG",
    "subtema_secundario": "",
    "extracto": "Se autoriza al Ejecutivo del Estado enajenar a título gratuito un predio de 12,852.91 m² a favor de la Comisión Federal de Electricidad (CFE) para la construcción de la 'Subestación Eléctrica Periférico Sur Banco 1', con el fin de mejorar confiabilidad y calidad del servicio eléctrico.",
    "resumen": "El pleno del Congreso autorizó al Ejecutivo estatal la transferencia gratuita de terreno a CFE para construir una subestación eléctrica en el Periférico Sur de Villahermosa. La obra busca mejorar la confiabilidad, continuidad y calidad del servicio de distribución eléctrica pública en la región. Importa porque es una acción concreta de gobernanza energética que fortalece la infraestructura de distribución de CFE en Tabasco.",
    "link_documento": "",
    "link_portal": "https://congresotabasco.gob.mx/autorizan-al-ejecutivo-del-estado-enajenar-predios-a-favor-de-la-comision-federal-de-electricidad-y-del-imss-bienestar/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: energía | Fecha aproximada (artículo publicado ~30 mar 2026)",
    "estado": "Tabasco"
  },
  {
    "id": "TAB-2025-012",
    "fecha": "2025-12-15",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Reforma a la Ley General de Tránsito y Vialidad del Estado de Tabasco para incorporar el concepto de 'Movilidad Integrada', entendida como operación del sistema de transporte con seguridad vial, accesibilidad, eficiencia, calidad y sustentabilidad articuladas.",
    "resumen": "El diputado Gerald Washington Herrera Castellanos (Movimiento Ciudadano) presentó una reforma para definir e incorporar la 'Movilidad Integrada' en la Ley General de Tránsito y Vialidad de Tabasco. El concepto establece que el sistema de transporte debe operar de manera articulada bajo principios de seguridad, accesibilidad, eficiencia y sustentabilidad. Importa porque actualiza el marco normativo para adaptarlo a los estándares contemporáneos de planificación de movilidad urbana.",
    "link_documento": "",
    "link_portal": "https://congresotabasco.gob.mx/iniciativas/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: movilidad | Presentada por Dip. Gerald Washington Herrera Castellanos (Movimiento Ciudadano)",
    "estado": "Tabasco"
  },
  {
    "id": "TAB-2025-011",
    "fecha": "2025-12-01",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Reforma a la Ley de Movilidad y a la Ley General de Tránsito y Vialidad del Estado de Tabasco para regular el servicio público de grúas y remolques, establecer tarifas por kilómetro, sistemas de asignación oficial por rotación y sanciones por cobros excesivos incluyendo revocación de concesión.",
    "resumen": "El diputado Jesús Ochoa Hernández presentó una reforma dual a la Ley de Movilidad y la Ley General de Tránsito para regular el cobro en servicios de grúas, remolques y pensiones vehiculares. La propuesta fija tarifas, crea un sistema rotatorio de asignación de grúas a través de autoridad oficial y establece sanciones hasta la revocación de concesión por abusos. Importa porque elimina prácticas de cobro abusivo que afectan directamente a conductores en situación de emergencia vial.",
    "link_documento": "",
    "link_portal": "https://congresotabasco.gob.mx/plantean-garantizar-cobro-de-tarifas-justas-y-transparentes-en-servicios-de-gruas-remolques-y-depositos-de-vehiculos/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | Sesión 1 dic 2025 | Presentada por Dip. Jesús Ochoa Hernández",
    "estado": "Tabasco"
  },
  {
    "id": "TAB-2025-009",
    "fecha": "2025-10-14",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Reforma a la Ley General de Tránsito y Vialidad del Estado de Tabasco para permitir que los trámites de renovación de licencia de conducir se realicen en línea, previa realización del pago correspondiente, ahorrando tiempo y recursos a los conductores.",
    "resumen": "La diputada Liliana Guadalupe Coutiño Peña (MORENA) presentó una reforma para digitalizar la renovación de licencias de conducir en Tabasco. La propuesta establece el pago previo en línea como requisito para gestionar el trámite sin acudir presencialmente. Importa porque moderniza la administración vial y reduce la burocracia para los conductores tabasqueños.",
    "link_documento": "",
    "link_portal": "https://congresotabasco.gob.mx/iniciativas/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: tránsito | Presentada por Dip. Liliana Guadalupe Coutiño Peña (MORENA)",
    "estado": "Tabasco"
  },
  {
    "id": "TAB-2025-001",
    "fecha": "2025-06-23",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_EF",
    "subtema_secundario": "",
    "extracto": "Se declara el 21 de octubre como 'Día Estatal del Ahorro de Energía' y se crea el 'Premio al Ahorro de Energía' que el Congreso otorgará a personas o entidades con aportaciones destacadas al ahorro y uso eficiente de la energía.",
    "resumen": "El Congreso aprobó en Comisión Permanente declarar el 21 de octubre como Día Estatal del Ahorro de Energía, con el fin de fomentar la conciencia ciudadana sobre el consumo responsable y eficiente de energía eléctrica. Adicionalmente se instituye un premio anual a quienes hayan contribuido significativamente al ahorro energético. Importa porque visibiliza la agenda de eficiencia energética en el estado y crea un mecanismo de reconocimiento institucional.",
    "link_documento": "https://congresotabasco.gob.mx/wp-content/uploads/2025/06/253.-Iniciativa-Dia-del-Ahorro-Energia.pdf",
    "link_portal": "https://congresotabasco.gob.mx/iniciativas/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: energía | Presentada por Dip. Francisco Donaldo López Chaires (MORENA)",
    "estado": "Tabasco"
  },
  {
    "id": "TAB-2025-005",
    "fecha": "2025-04-01",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "MOV_TP",
    "extracto": "Reforma al artículo 140 de la Ley de Movilidad para el Estado de Tabasco a fin de garantizar el acceso gratuito al servicio de transporte público a personas con discapacidad que presenten identificación vigente expedida por institución autorizada.",
    "resumen": "El diputado Francisco Javier Cabrera Sandoval (PRD) propuso modificar la Ley de Movilidad para que el transporte público sea gratuito para personas con discapacidad acreditada. La propuesta fue turnada a la Comisión de Tránsito y Movilidad para su análisis. Importa porque avanza en la garantía del derecho a la movilidad como servicio accesible para poblaciones con necesidades especiales.",
    "link_documento": "",
    "link_portal": "https://congresotabasco.gob.mx/recibe-congreso-propuestas-en-materia-de-movilidad-pecuaria-y-educativa/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: movilidad | Presentada por Dip. Francisco Javier Cabrera Sandoval (PRD) | Turnada a Comisión de Tránsito y Movilidad",
    "estado": "Tabasco"
  },
  {
    "id": "TAB-2025-003",
    "fecha": "2025-03-25",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Exhorto a la Secretaría de Movilidad del Estado para atender la falta de unidades de transporte público en diversas avenidas de la capital, solicitando estrategias para mejorar el servicio y asignar unidades suficientes en las rutas deficitarias.",
    "resumen": "Un diputado de Movimiento Ciudadano presentó un exhorto para que la Secretaría de Movilidad atienda la escasez de transporte público en avenidas específicas de Villahermosa. La propuesta pide estrategias para ampliar cobertura y mejorar el servicio a los usuarios. Importa porque evidencia déficit en la red de transporte público concesionado en la zona metropolitana.",
    "link_documento": "",
    "link_portal": "https://congresotabasco.gob.mx/da-entrada-mesa-directiva-a-diversas-propuestas-presentadas-por-las-y-los-integrantes-de-la-lxv-legislatura/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | Sesión 25 mar 2025 | Presentada por diputado Movimiento Ciudadano (nombre sin confirmar)",
    "estado": "Tabasco"
  },
  {
    "id": "TAB-2025-004",
    "fecha": "2025-03-25",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "MOV_ACT",
    "extracto": "Reforma a diversas disposiciones de la Ley de Asentamientos Humanos, Ley de Movilidad y Ley de Obras Públicas para exigir infraestructura vial urbana adecuada e inclusiva, incorporando estándares de accesibilidad para personas con discapacidad en la planificación territorial.",
    "resumen": "El coordinador parlamentario del PRI presentó una reforma que vincula la planificación territorial con la infraestructura de movilidad, incorporando requisitos de accesibilidad para personas con discapacidad. La propuesta modifica tres leyes para garantizar que obras públicas viales y asentamientos contemplen transporte público inclusivo. Importa porque integra la perspectiva de accesibilidad en la obra pública desde la fase de planeación.",
    "link_documento": "",
    "link_portal": "https://congresotabasco.gob.mx/da-entrada-mesa-directiva-a-diversas-propuestas-presentadas-por-las-y-los-integrantes-de-la-lxv-legislatura/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: movilidad | Sesión 25 mar 2025 | Presentada por coordinador PRI",
    "estado": "Tabasco"
  },
  {
    "id": "TAB-2025-002",
    "fecha": "",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "Exhorto al Director General de la CFE para que cese los cortes de suministro eléctrico y cancele las notificaciones extrajudiciales enviadas a familias tabasqueñas por adeudos, considerando la situación económica de la población.",
    "resumen": "La diputada Sheila Guadalupe Cadena Nieto presentó un punto de acuerdo para exhortar a la CFE a detener los cortes de luz a usuarios domésticos y cancelar los cobros coercitivos por deuda. La iniciativa responde a quejas ciudadanas sobre interrupciones del servicio y prácticas de cobro agresivas en Tabasco. Importa porque pone en la agenda legislativa los abusos tarifarios y de servicio de CFE frente a las familias de menores ingresos.",
    "link_documento": "",
    "link_portal": "https://congresotabasco.gob.mx/iniciativas/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: energía | Presentada por Dip. Sheila Guadalupe Cadena Nieto | Fecha pendiente de verificar en portal",
    "estado": "Tabasco"
  },
  {
    "id": "TAB-2025-006",
    "fecha": "",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Reforma a la Ley de Movilidad para obligar a las unidades de transporte público concesionado a contar con sistema de audio que anuncie números de terminal, ubicaciones y rutas, facilitando el uso del servicio a personas con discapacidad visual.",
    "resumen": "Un diputado del PRD presentó una reforma a la Ley de Movilidad para que todas las unidades de transporte público cuenten con sistema de sonido que informe sobre terminales y rutas. La medida busca eliminar barreras de acceso para personas con discapacidad visual o de otro tipo que no pueden leer los letreros. Importa porque incorpora un estándar mínimo de inclusión tecnológica en el transporte público.",
    "link_documento": "",
    "link_portal": "https://congresotabasco.gob.mx/iniciativas/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: movilidad | Presentada por diputado PRD (nombre sin confirmar) | Fecha pendiente de verificar",
    "estado": "Tabasco"
  },
  {
    "id": "TAB-2025-007",
    "fecha": "",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado en Comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Reforma a la Ley General de Tránsito y Vialidad del Estado de Tabasco para establecer como requisito indispensable la presentación de constancia de educación vial al solicitar licencia de conducir por primera vez.",
    "resumen": "La Comisión correspondiente aprobó en dictamen una reforma a la Ley General de Tránsito y Vialidad que exige constancia de educación vial para obtener la primera licencia de conducir. La medida busca que los nuevos conductores tengan formación básica en normas de tránsito antes de recibir su licencia. Importa porque fortalece la cultura vial desde el punto de entrada al sistema de conducción.",
    "link_documento": "",
    "link_portal": "https://congresotabasco.gob.mx/aprueban-en-comision-establecer-como-requisito-constancia-de-educacion-vial-para-solicitar-licencia-de-conducir-por-primera-vez/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado en Comisión | Término búsqueda: tránsito | Fecha pendiente de verificar en portal",
    "estado": "Tabasco"
  },
  {
    "id": "TAB-2025-008",
    "fecha": "",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Reforma a diversas disposiciones de la Ley General de Tránsito y Vialidad y la Ley de Hacienda del Estado para eliminar la obligatoriedad de renovación de placas vehiculares (salvo robo, pérdida o deterioro) y establecer la licencia de conducir permanente.",
    "resumen": "El diputado Fabián Granier Calles (PRI) propuso reformar la Ley General de Tránsito y la Ley de Hacienda para suprimir la renovación periódica obligatoria de placas y hacer permanentes las licencias de conducir. La propuesta busca reducir cargas administrativas y económicas para los conductores. Importa porque eliminaría una fuente recurrente de ingresos por trámites y puede afectar el sistema de control vehicular.",
    "link_documento": "",
    "link_portal": "https://congresotabasco.gob.mx/iniciativas/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: tránsito | Presentada por Dip. Fabián Granier Calles (PRI) | Fecha pendiente de verificar",
    "estado": "Tabasco"
  },
  {
    "id": "TAB-2025-010",
    "fecha": "",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Reforma a la Ley General de Tránsito y Vialidad para otorgar facilidades a personas con discapacidad en los procedimientos administrativos de tramitación y en la presentación del examen para obtener licencia de conducir, adecuando las pruebas a sus capacidades.",
    "resumen": "La propuesta busca que las personas con discapacidad puedan acceder al trámite de licencia de conducir con adaptaciones en el examen y en los procesos administrativos. Fue turnada a la Comisión de Tránsito y Movilidad para su estudio. Importa porque reconoce el derecho de personas con discapacidad a conducir y acceder a la movilidad activa individual.",
    "link_documento": "",
    "link_portal": "https://congresotabasco.gob.mx/iniciativas/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: tránsito | Presentada ≈ octubre 2025 | Fecha exacta pendiente de verificar | Subtema corregido: MOV_SEG→MOV_ACT (la reforma reconoce accesibilidad como derecho, no solo sanciones/trámites)",
    "estado": "Tabasco"
  }
];

const SUBTEMAS = {
  "ENE_GEN": "Generación y transición energética",
  "ENE_REG": "Marco regulatorio energético",
  "ENE_TAR": "Tarifas, subsidios y cortes de suministro",
  "ENE_HC": "Hidrocarburos, gas y combustibles",
  "ENE_EF": "Eficiencia energética y alumbrado",
  "MOV_SEG": "Seguridad vial",
  "MOV_INF": "Infraestructura vial",
  "MOV_ACT": "Movilidad activa",
  "MOV_TP": "Transporte público y concesiones",
  "MOV_ELEC": "Electromovilidad y vehículos eléctricos"
};
