const DATA = [
  {
    "id": "NAY-2025-002",
    "fecha": "2025-12-10",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Nueva Ley de Vías de Comunicación del Estado de Nayarit compuesta por 67 artículos distribuidos en 11 capítulos y 3 artículos transitorios. Regula el uso, protección, administración y aprovechamiento del derecho de vía en infraestructura carretera estatal, incluyendo control estricto de anuncios espectaculares y señalética vial, reemplazando una ley de 42 años de antigüedad.",
    "resumen": "La XXXIV Legislatura de Nayarit aprobó una nueva Ley de Vías de Comunicación que actualiza una legislación con más de cuatro décadas de vigencia. La nueva ley, enviada por el gobernador Miguel Ángel Navarro Quintero, establece criterios modernos para la preservación, vigilancia y administración de infraestructura carretera, con énfasis en el control de anuncios publicitarios en zonas estratégicas. Su aprobación permitirá planificar y supervisar mejor las carreteras estatales, fortaleciendo la regulación urbana, la seguridad vial y la protección ambiental.",
    "link_documento": "",
    "link_portal": "https://congresonayarit.gob.mx/nayarit-moderniza-su-legislacion-de-vias-de-comunicacion-tras-42-anos/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: vialidad | Promovida por el Ejecutivo estatal (gobernador Navarro Quintero); fecha de aprobación en sesión dic-2025; publicación en POEN pendiente de verificar",
    "estado": "Nayarit"
  },
  {
    "id": "NAY-2025-001",
    "fecha": "2025-07-01",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa del Grupo Parlamentario del PAN que reforma el artículo 263 de la Ley de Movilidad del Estado de Nayarit para establecer que las sesiones de la Comisión Técnica de Movilidad sean públicas y se transmitan en vivo, garantizando transparencia en el proceso de otorgamiento de concesiones de transporte público.",
    "resumen": "La bancada del PAN presentó una iniciativa para reformar el artículo 263 de la Ley de Movilidad con el fin de obligar a la Comisión Técnica de Movilidad a celebrar sus sesiones de forma pública y transmitirlas en tiempo real. La propuesta responde a la opacidad observada en los procesos de otorgamiento de concesiones de transporte. Si se aprobara, representaría un avance significativo en la transparencia y rendición de cuentas del sector transporte público en Nayarit.",
    "link_documento": "https://parlamentoabierto.congresonayarit.gob.mx/files/729_KsCDP_INICIATIVA%20REF.%20ART.%20263%20LEY%20MOVILIDAD%20EDO%20NAYARIT%20-%20GRUPO%20PARLAMENTARIO%20PAN.pdf",
    "link_portal": "https://parlamentoabierto.congresonayarit.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada (no verificado) | Término búsqueda: transporte | Fecha estimada; archivo 729 en Parlamento Abierto sugiere XXXIV legislatura 2025",
    "estado": "Nayarit"
  },
  {
    "id": "NAY-2024-003",
    "fecha": "2024-10-25",
    "tipo_acto": "Minuta",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_INF",
    "extracto": "Minuta de Decreto que reforma el párrafo cuarto y adiciona un párrafo quinto al artículo 28 de la Constitución Política de los Estados Unidos Mexicanos en materia de vías y transporte ferroviario. Nayarit fue una de las 24 legislaturas estatales que ratificaron esta reforma constitucional federal, publicada en DOF el 29-oct-2024.",
    "resumen": "El Congreso de Nayarit ratificó la reforma constitucional que habilita al Estado mexicano a utilizar las vías ferroviarias para el transporte de pasajeros, permitiendo asignaciones a empresas públicas y concesiones a privados. La reforma fue declarada constitucional por la Cámara de Diputados tras la ratificación de 24 estados, entre ellos Nayarit. Representa un cambio estratégico en política de movilidad al recuperar capacidad estatal en infraestructura ferroviaria de largo plazo.",
    "link_documento": "",
    "link_portal": "https://procesolegislativo.congresonayarit.gob.mx/iniciativas/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte | Publicada en DOF 29-oct-2024; Nayarit entre los 24 estados ratificadores; fecha de votación estimada (aprox. oct 2024)",
    "estado": "Nayarit"
  },
  {
    "id": "NAY-2024-004",
    "fecha": "2024-09-15",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Punto de acuerdo que exhorta a la Secretaría de Infraestructura, Comunicaciones y Transportes (SICT) federal a resolver el pago de indemnizaciones pendientes a ejidatarios afectados por la construcción de la carretera Tepic-Matanchén en el Estado de Nayarit.",
    "resumen": "El Dip. Diego Cristóbal Calderón Estrada presentó un Punto de Acuerdo para exhortar a la autoridad federal de infraestructura a pagar compensaciones adeudadas a ejidatarios por la construcción de la carretera Tepic-Matanchén. Se trata de un exhorto no vinculante que busca atender una deuda histórica del gobierno federal con comunidades rurales afectadas por obra vial en Nayarit. El caso evidencia rezagos en la regularización de derechos de vía para proyectos carreteros estatales.",
    "link_documento": "",
    "link_portal": "https://procesolegislativo.congresonayarit.gob.mx/iniciativas/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: vialidad | Fecha estimada (XXXIV legislatura; inicio agosto 2024); presentante: Dip. Diego Cristóbal Calderón Estrada",
    "estado": "Nayarit"
  },
  {
    "id": "NAY-2024-001",
    "fecha": "2024-04-17",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "MOV_TP",
    "extracto": "Reforma y adición a múltiples artículos de la Ley de Movilidad del Estado de Nayarit para armonizarla con la Ley General de Movilidad y Seguridad Vial. Renombra el Capítulo I del Título Segundo como 'Del Derecho a la Movilidad' e incorpora principios de movilidad sostenible, participación ciudadana y coordinación metropolitana.",
    "resumen": "El Congreso de Nayarit aprobó el Decreto 399 que armoniza la Ley de Movilidad estatal con la Ley General de Movilidad y Seguridad Vial. La reforma establece el derecho universal a la movilidad en condiciones de seguridad, accesibilidad y sostenibilidad, e incorpora mecanismos de participación ciudadana y coordinación entre municipios. Su aprobación actualiza el marco normativo para cumplir estándares federales y reduce el riesgo de inconsistencias entre legislación estatal y federal.",
    "link_documento": "https://procesolegislativo.congresonayarit.gob.mx/archivos/leyes_decretos/399-publicacion-PUBLICACI%C3%93N%20DECRETO%20REF.%20LEY%20MOVILIDAD%20ARMONIZACI%C3%93N%20LEY%20GRAL..pdf",
    "link_portal": "https://procesolegislativo.congresonayarit.gob.mx/iniciativas/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: movilidad | Decreto 399 publicado en Periódico Oficial del Estado de Nayarit el 17-abr-2024",
    "estado": "Nayarit"
  },
  {
    "id": "NAY-2024-002",
    "fecha": "2024-03-01",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Reforma a la Ley de Movilidad del Estado de Nayarit en materia de accesibilidad universal para personas con discapacidad o movilidad reducida. Incluye disposiciones sobre infraestructura de transporte accesible e integración de estos grupos vulnerables en el sistema de movilidad estatal.",
    "resumen": "El Congreso de Nayarit aprobó el Decreto 356 que reforma la Ley de Movilidad para garantizar los derechos de personas con discapacidad y movilidad reducida en el sistema de transporte. Las modificaciones establecen obligaciones de accesibilidad universal para la infraestructura vial y el transporte público. Representa un avance en la inclusión de grupos vulnerables en la planificación de la movilidad conforme a estándares de derechos humanos.",
    "link_documento": "https://procesolegislativo.congresonayarit.gob.mx/archivos/leyes_decretos/356-publicacion-PUBLICACI%C3%93N%20DECRETO%20REFORMA%20LEY%20MOVILIDAD%20PERSONAS%20DISCAPACIDAD.pdf",
    "link_portal": "https://procesolegislativo.congresonayarit.gob.mx/iniciativas/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: movilidad | Decreto 356 en POEN; fecha estimada (día exacto no confirmado; registro de reforma anterior a Decreto 399 de abril 2024)",
    "estado": "Nayarit"
  },
  {
    "id": "NAY-2022-002",
    "fecha": "2022-08-11",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En dictamen",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Reforma a la Ley de Movilidad del Estado de Nayarit que establece que las concesiones o permisos de transporte público son imprescriptibles, inalienables e intransferibles, no podrán ser heredadas ni embargadas, y no son objeto de transmisión por muerte, donación, herencia o legado.",
    "resumen": "La Comisión de Obras Públicas, Comunicaciones y Transportes aprobó un dictamen que reforma la Ley de Movilidad para prohibir la transferencia, herencia o embargo de concesiones de transporte público. La medida busca erradicar la comercialización informal de permisos y el modelo ineficiente del 'hombre-camión'. Su aprobación en pleno modernizaría la regulación del sector y daría mayor control estatal sobre el sistema de transporte público concesionado.",
    "link_documento": "",
    "link_portal": "https://congresonayarit.gob.mx/concesiones-de-transporte-publico-no-podran-ser-heredadas/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En dictamen (comisión 11-ago-2022) | Término búsqueda: transporte | Aprobación en pleno programada para cuarta sesión extraordinaria; resultado final no verificado",
    "estado": "Nayarit"
  },
  {
    "id": "NAY-2022-001",
    "fecha": "2022-04-05",
    "tipo_acto": "Dictamen",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Iniciativa que adiciona el inciso o) a la fracción IV del artículo 432 de la Ley de Movilidad del Estado de Nayarit para establecer la distancia mínima de seguridad que deben guardar los vehículos motorizados al adelantar o rebasar a ciclistas en vías públicas.",
    "resumen": "El Dip. Alejandro Regalado Curiel presentó una iniciativa para proteger a los ciclistas mediante la regulación de la distancia de seguridad entre vehículos y bicicletas. Existe un dictamen de comisión en el expediente, aunque el estatus de aprobación en pleno no ha podido verificarse. La medida busca reducir accidentes de tránsito y mejorar la convivencia entre distintos modos de transporte en las vías de Nayarit.",
    "link_documento": "https://procesolegislativo.congresonayarit.gob.mx/wp-content/uploads/sesiones/9oBCmeEjYG_86_DICT_REF_LEY_MOVILIDAD_-DISTANCIA_CICLISTAS_ART_432.pdf",
    "link_portal": "https://procesolegislativo.congresonayarit.gob.mx/iniciativas/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio (no confirmado) | Término búsqueda: movilidad | Fecha es la de presentación de la iniciativa; existe dictamen de comisión pero estatus en pleno no verificado",
    "estado": "Nayarit"
  }
];

const SUBTEMAS = {
  "ENE_GEN": "Generación y transición energética",
  "ENE_REG": "Marco regulatorio energético",
  "ENE_TAR": "Tarifas, subsidios y cortes de suministro",
  "ENE_HC": "Hidrocarburos, gas y combustibles",
  "ENE_EF": "Eficiencia energética y alumbrado",
  "MOV_SEG": "Seguridad vial",
  "MOV_INF": "Infraestructura vial",
  "MOV_ACT": "Movilidad activa",
  "MOV_TP": "Transporte público y concesiones",
  "MOV_ELEC": "Electromovilidad y vehículos eléctricos"
};
